---
# file: roles/nginx/vars/main.yml
# variables associated with this role

##
# fastcgi_params
##

query_string:  $query_string
request_method:  $request_method
content_type:  $content_type
content_length:  $content_length

script_name: $fastcgi_script_name
request_uri: $request_uri
document_uri:  $document_uri
document_root: $document_root
server_protocol: $server_protocol
request_scheme:  $scheme
https: $https if_not_empty

gateway_interface: CGI/1.1
server_software: nginx/$nginx_version

remote_addr: $remote_addr
remote_port: $remote_port
server_addr: $server_addr
server_port: $server_port
server_name: $server_name

redirect_status: 200
