---
# roles/deploy/handlers/main.yml

- name: Restart Nginx
  command:
    sudo /usr/sbin/service nginx restart
    warn=False

- name: Restart php7.2-fpm
  command:
    sudo /usr/sbin/service php7.2-fpm restart
    warn=False
  when: php_version is not defined or php_version == 7.2
