---
# file: roles/nginx/handlers/main.yml

- name: Test and Restart Nginx
  become: yes
  command: nginx -t
  notify: Restart Nginx

- name: Restart Nginx
  become: yes
  service: name=nginx state=restarted
