---
- import_tasks: include-vars.yml

- import_tasks: install-with-package.yml
  become: yes
  when: not certbot_install_from_source
  tags: certbot

- import_tasks: install-from-source.yml
  become: yes
  when: certbot_install_from_source
  tags: certbot

- include_tasks: create-cert-standalone.yml
  become: yes
  with_items: "{{ certbot_certs }}"
  when:
    - certbot_create_if_missing
    - certbot_create_method == 'standalone'
  loop_control:
    loop_var: cert_item
  tags: certbot

- import_tasks: renew-cron.yml
  when: certbot_auto_renew
  tags: certbot
