---
# file: roles/common/tasks/hosts.yml

##
# HOSTS
##

- name: Ensure Hosts are defined
  become: yes
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item.name }}$'
    line: "{{ item.ip }} {{ item.name }}"
    state: present
  with_items: "{{ hostvars[inventory_hostname].hosts }}"
  tags:
    - common
    - hosts
